stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: fbsanchez/httpphp:7-runner
  script:
    - composer install
  cache:
    key: umc0000
    paths:
      - vendor

test:
  stage: test
  image: docker:stable
  cache:
    key: umc0000
    paths:
      - vendor
  variables:
    DOCKER_DRIVER: overlay2
  script:
    # Login into registry
    - docker login -u artica -p $CI_LOGIN_REG aiur.artica.lan:5000
    - docker pull aiur.artica.lan:5000/um:${CI_COMMIT_REF_SLUG}
    - docker run -v $(pwd):/root/code/client -e TEST=client -e DB=1 --rm --name test.taldarim.artica.lan_${CI_COMMIT_REF_SLUG} -i aiur.artica.lan:5000/um:${CI_COMMIT_REF_SLUG}
  only:
    - branches

# Generate a package into packages register
deploy_composer:
  when: manual
  only:
    - tags
  stage: deploy
  image: alpine/curl
  script:
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "https://__token__:${PACKAGE_DEPLOY_TOKEN}@${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/composer"
